services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php_yii2
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=yii2_database
      - DB_USER=yii2_user
      - DB_PASSWORD=yii2_password
    command: /usr/local/bin/start.sh

  db:
    image: mysql:8.0
    container_name: mysql_yii2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: yii2_database
      MYSQL_USER: yii2_user
      MYSQL_PASSWORD: yii2_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
